[package]
name = "raddy"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.89"
env_logger = "0.11.8"
http = "1.4.0"
log = "0.4.29"
pingora = { version = "0.6.0", features = ["lb", "proxy", "rustls"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_yaml = "0.9.34"
tokio = { version = "1.49.0", features = ["full"] }
url = "2.5.8"
